name: chartevents
path: icu/chartevents.csv.gz
version: "3.1"
dataset: mimic-iv

columns:
  
  # subject_id and extentions
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
  - name: subject_id
    type: int64
  # db fields - times
  - name: charttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: caregiver_id
    type: int64
  - name: itemid
    type: int64
  - name: value
    type: string
  - name: valuenum
    type: float32
  - name: valueuom
    type: string
  - name: warning
    type: int64

join:
  - name: d_items
    path: icu/d_items.csv.gz
    columns:
      # subject_id and extentions
      # db fields - times
      # db fields - values
      - name: itemid
        type: int64
      - name: label
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: col(subject_id)
  code_prefix:
    - const("icu/chartevents")
  extension:
    hadm_id: col(hadm_id)
    stay_id: col(stay_id)
    src_db_id: const("mimic")

events:
  - name: caregiver_store
    columns:
      time: col(storetime)
      code:
        - const("CG_ST")
      numeric_value: col(caregiver_id)
  - name: chartevent
    columns:
      time: col(charttime)
      code:
        - const("chartevent")
        - col(label)
        - col(valueuom)
      numeric_value: col(valuenum)
      text_value: col(value)
  - name: warning
    columns:
      time: col(storetime)
      code:
        - const("WARNING")
      numeric_value: col(warning)
    filters:
      - drop_na(numeric_value)
