name: drgcodes
path: hosp/drgcodes.csv.gz
version: "3.1"
dataset: mimic-iv

columns:
  # subject_id and extentions
  - name: hadm_id
    type: int64
  - name: subject_id
    type: int64
  # db fields - times
  # db fields - values
  - name: description
    type: string
  - name: drg_code
    type: string
  - name: drg_mortality
    type: int64
  - name: drg_severity
    type: int64
  - name: drg_type
    type: string

join:
  - name: admissions
    path: hosp/admissions.csv.gz
    columns:
      # subject_id and extensions
      - name: subject_id
        type: int64
      # db fields - times
      - name: admittime
        type: datetime
        params:
          format: "%Y-%m-%d %H:%M:%S"
      # db fields - values
    both_on:
      - subject_id

event_defaults:
  subject_id: col(subject_id)
  time: col(admittime)
  code_prefix:
    - col(drg_type)
    - col(drg_code)
  extension:
    hadm_id: col(hadm_id)
    stay_id: const("-1")

events:
  - name: drg_code
    columns:
      code:
        - const("DRG_CODE")
      text_value: col(description)
  - name: drg_severity
    columns:
      code:
        - const("DRG_SEVERITY")
      numeric_value: col(drg_severity)
  - name: drg_mortality
    columns:
      code:
        - const("DRG_MORTALITY")
      numeric_value: col(drg_mortality)
