name: emar
path: hosp/emar.csv
version: "3.1"
dataset: mimic-iv

fields:
  # general codes
  - name: src_table_code
    type: string
    constant: hosp/emar
  # codes
  - name: scheduletime_code
    type: string
    constant: SCHEDULETIME
  # subject_id and extentions
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
    constant: -1
  - name: src_db_id
    type: string
    constant: mimic
  - name: subject_id
    type: int64
  # db fields - times
  - name: charttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: scheduletime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: emar_id  # emar = subject_id + "-" + emar_seq
    type: string
  - name: emar_seq
    type: int64
  - name: enter_provider_id
    type: string
  - name: event_txt
    type: string
  - name: medication
    type: string
  - name: pharmacy_id
    type: int64
  - name: poe_id
    type: string

event_defaults:
  subject_id: subject_id
  code_prefix:
    - src_table_code
  extension:
    hadm_id: hadm_id
    stay_id: stay_id
    src_db_id: src_db_id

events:
  - name: diagnoses
    fields:
      time: charttime
      code:
        - medication
      text_value: event_txt
  - name: scheduletime
    fields:
      time: scheduletime
      code:
        - scheduletime_code
