name: hcpcsevents
path: hosp/hcpcsevents.csv

fields:
  # general code
  - name: source_db_code
    type: string
    constant: mimic 
  - name: source_table_code
    type: string
    constant: hosp/hcpcsevents
  # codes
  - name: hcspsevents_code
    type: string
    constant: HCPCS
  # subject_id and extentions
  - name: hadm_id
    type: int64[pyarrow]
  - name: stay_id
    type: int64
    constant: -1
  - name: subject_id
    type: int64
  # db fields
  - name: chartdate
    type: datetime
  - name: hcpcs_cd
    type: string
  - name: seq_num
    type: int64
  - name: short_description
    type: string[pyarrow]

events: 
  - name: hpcsevent
    fields:
      subject_id: subject_id
      time: chartdate
      code: 
        - source_db_code
        - source_table_code
        - hcspsevents_code
        - hcpcs_cd
      numeric_value: seq_num
      text_value: short_description
      extension:
          hadm_id: hadm_id
          stay_id: stay_id