name: hcpcsevents
path: hosp/hcpcsevents.csv.gz
version: "3.1"
dataset: mimic-iv

columns:
  # subject_id and extentions
  - name: hadm_id
    type: int64
  - name: subject_id
    type: int64
  # db fields - times
  - name: chartdate
    type: datetime
    params:
      format: "%Y-%m-%d"
  # db fields - values
  - name: hcpcs_cd
    type: string
  - name: seq_num
    type: int64
  - name: short_description
    type: string

events:
  - name: hcpcsevent
    columns:
      subject_id: col(subject_id)
      time: col(chartdate)
      code:
        - const("HCPCS")
        - col(hcpcs_cd)
      numeric_value: col(seq_num)
      text_value: col(short_description)
      extension:
          hadm_id: col(hadm_id)
          stay_id: const("-1")
