name: ingredientevents
path: icu/ingredientevents.csv

fields:
  # general codes
  - name: src_table_code
    type: string
    constant: icu/ingredientevents
  # codes
  - name: amount_code
    type: string
    constant: DOSAGE
  - name: caregiver_store_code
    type: string
    constant: CG_ST # caregiver_storetime
  - name: linkorder_code
    type: string
    constant: LINKORDER
  - name: order_code
    type: string
    constant: ORDER
  - name: originalamount_code
    type: string
    constant: ORIGINAL_DOSAGE
  - name: originalrate_code
    type: string
    constant: ORIGINALRATE
  - name: rate_end_code
    type: string
    constant: RATE_END
  - name: rate_start_code
    type: string
    constant: RATE_START
  - name: statusdescription_code
    type: string
    constant: STATUSDESCRIPTION
  # subject_id and extensions
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
  - name: src_db_id
    type: string
    constant: mimic
  - name: subject_id
    type: int64
    # db fields - times
  - name: endtime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: starttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
    # db fields - values
  - name: amount
    type: float32
  - name: amountuom
    type: string
  - name: caregiver_id
    type: int64
  - name: itemid
    type: int64
  - name: linkorderid
    type: int64
  - name: orderid
    type: int64
  - name: originalamount
    type: int64
  - name: originalrate
    type: float32 
  - name: rate
    type: float32
  - name: rateuom
    type: string
  - name: statusdescription
    type: string
    
join:
  - name: d_items
    path: icu/d_items.csv
    fields:
      # general codes
      # codes
      # subject_id and extensions
      # db fields - times
      # db fields - values
      - name: itemid
        type: int64
      - name: label
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: subject_id
  code_prefix:
    - src_table_code
  extension:
    hadm_id: hadm_id
    stay_id: stay_id
    src_db_id: src_db_id

events:
  - name: caregiver_store
    fields: 
      time: storetime
      code: 
        - caregiver_store_code
      numeric_value: caregiver_id
  - name: rate_start
    fields:
      time: starttime
      code:
        - rate_start_code
        - label
        - rateuom
      numeric_value: rate 
    callbacks:
      - callback: drop_na
        params: 
          columns:
            - numeric_value
  - name: rate_end
    fields:
      time: endtime
      code:
        - rate_end_code
        - label
        - rateuom
      numeric_value: rate
    callbacks:
      - callback: drop_na
        params: 
          columns:
            - numeric_value
  - name: dosage
    fields:
      time: endtime
      code: 
        - amount_code
        - label
        - amountuom
      numeric_value: amount
  - name: order
    fields:
      time: endtime
      code:
        - order_code
      numeric_value: orderid
  - name: linkorder
    fields: 
      time: endtime
      code: 
        - linkorder_code
      numeric_value: linkorderid  
  - name: statusdescription
    fields:
      time: endtime
      code: 
        - statusdescription_code
        - statusdescription
  - name: originalrate
    fields:
      time: starttime
      code:
        - originalrate_code
        - label
        - rateuom
      numeric_value: originalrate
    callbacks:
      - callback: drop_na
        params: 
          columns:
            - numeric_value