name: ingredientevents
path: icu/ingredientevents.csv.gz
version: "3.1"
dataset: mimic-iv

columns:
  # subject_id and extensions
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
  - name: subject_id
    type: int64
    # db fields - times
  - name: endtime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: starttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
    # db fields - values
  - name: amount
    type: float32
  - name: amountuom
    type: string
  - name: caregiver_id
    type: int64
  - name: itemid
    type: int64
  - name: linkorderid
    type: int64
  - name: orderid
    type: int64
  - name: originalamount
    type: int64
  - name: originalrate
    type: float32
  - name: rate
    type: float32
  - name: rateuom
    type: string
  - name: statusdescription
    type: string

join:
  - name: d_items
    path: icu/d_items.csv.gz
    columns:
      # subject_id and extensions
      # db fields - times
      # db fields - values
      - name: itemid
        type: int64
      - name: label
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: col(subject_id)
  code_prefix:
    - const("icu/ingredientevents")
  extension:
    hadm_id: col(hadm_id)
    stay_id: col(stay_id)
    src_db_id: const("mimic")

events:
  - name: caregiver_store
    columns:
      time: col(storetime)
      code:
        - const("CG_ST")
      numeric_value: col(caregiver_id)
  - name: rate_start
    columns:
      time: col(starttime)
      code:
        - const("RATE_START")
        - col(label)
        - col(rateuom)
      numeric_value: col(rate)
    filters:
      - drop_na(numeric_value)
  - name: rate_end
    columns:
      time: col(endtime)
      code:
        - const("RATE_END")
        - col(label)
        - col(rateuom)
      numeric_value: col(rate)
    filters:
      - drop_na(numeric_value)
  - name: dosage
    columns:
      time: col(endtime)
      code:
        - const("DOSAGE")
        - col(label)
        - col(amountuom)
      numeric_value: col(amount)
  - name: order
    columns:
      time: col(endtime)
      code:
        - const("ORDER")
      numeric_value: col(orderid)
  - name: linkorder
    columns:
      time: col(endtime)
      code:
        - const("LINKORDER")
      numeric_value: col(linkorderid)
  - name: statusdescription
    columns:
      time: col(endtime)
      code:
        - const("STATUSDESCRIPTION")
        - col(statusdescription)
  - name: originalrate
    columns:
      time: col(starttime)
      code:
        - const("ORIGINALRATE")
        - col(label)
        - col(rateuom)
      numeric_value: col(originalrate)
    filters:
      - drop_na(numeric_value)
