name: ingredientevents
path: icu/ingredientevents.csv

fields:
    # general code
    - name: source_db_code
      type: string
      constant: mimic
    - name: source_table_code
      type: string
      constant: icu/ingredientevents
    # codes
    - name: amount_code
      type: string
      constant: DOSAGE
    - name: caregiver_store_code
      type: string
      constant: CG_ST # caregiver_storetime
    - name: linkorder_code
      type: string
      constant: LINKORDER
    - name: order_code
      type: string
      constant: ORDER
    - name: originalamount_code
      type: string
      constant: ORIGINAL_DOSAGE
    - name: originalrate_code
      type: string
      constant: ORIGINALRATE
    - name: rate_end_code
      type: string
      constant: RATE_END
    - name: rate_start_code
      type: string
      constant: RATE_START
    - name: statusdescription_code
      type: string
      constant: STATUSDESCRIPTION
    # subject_id and extentions
    - name: hadm_id
      type: int64
    - name: stay_id
      type: int64
    - name: subject_id
      type: int64
    # db fields
    - name: amount
      type: float32
    - name: amountuom
      type: string
    - name: caregiver_id
      type: int64
    - name: endtime
      type: datetime
    - name: itemid
      type: int64
    - name: linkorderid
      type: int64
    - name: orderid
      type: int64
    - name: originalamount
      type: int64
    - name: originalrate
      type: float32 
    - name: rate
      type: float32
    - name: rateuom
      type: string
    - name: starttime
      type: datetime
    - name: statusdescription
      type: string
    - name: storetime
      type: datetime
      
join:
  - name: d_items
    path: icu/d_items.csv
    fields:
      # general code
      # codes
      # subject_id and extentions
      # db fields
      - name: itemid
        type: int64
      - name: label
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: subject_id
  extension:
    hadm_id: hadm_id
    stay_id: stay_id
  code_prefix:
    - source_db_code
    - source_table_code

events:
  - name: caregiver_store
    fields: 
      time: storetime
      code: 
        - caregiver_store_code
      numeric_value: caregiver_id
  - name: rate_start
    fields:
      time: starttime
      code:
        - rate_start_code
        - label
        - rateuom
      numeric_value: rate 
    callbacks:
      - callback: drop_na
        params: 
          columns:
            - numeric_value
  - name: rate_end
    fields:
      time: endtime
      code:
        - rate_end_code
        - label
        - rateuom
      numeric_value: rate
    callbacks:
      - callback: drop_na
        params: 
          columns:
            - numeric_value
  - name: dosage
    fields:
      time: endtime
      code: 
        - amount_code
        - label
        - amountuom
      numeric_value: amount
  - name: order
    fields:
      time: endtime
      code:
        - order_code
      numeric_value: orderid
  - name: linkorder
    fields: 
      time: endtime
      code: 
        - linkorder_code
      numeric_value: linkorderid  
  - name: statusdescription
    fields:
      time: endtime
      code: 
        - statusdescription_code
        - statusdescription
  - name: originalrate
    fields:
      time: starttime
      code:
        - originalrate_code
        - label
        - rateuom
      numeric_value: originalrate
    callbacks:
      - callback: drop_na
        params: 
          columns:
            - numeric_value