name: inputevents
path: icu/inputevents.csv.gz
version: "3.1"
dataset: mimic-iv

columns:
  # subject_id and extentions
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
  - name: subject_id
    type: int64
  # db fields - times
  - name: endtime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: starttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: amount
    type: float32
  - name: amountuom
    type: string
  - name: itemid
    type: int64
  - name: rate
    type: float32
  - name: rateuom
    type: string

join:
  - name: d_items
    path: icu/d_items.csv.gz
    columns:
      # subject_id and extentions
      # db fields - times
      # db fields - values
      - name: itemid
        type: int64
      - name: label
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    stay_id: col(stay_id)

events:
  - name: dosage
    columns:
      time: col(endtime)
      code:
        - col(label)
        - col(amountuom)
      numeric_value: col(amount)
    filters:
      - drop_na(numeric_value)
  - name: rate
    columns:
      time: col(starttime)
      code:
        - col(label)
        - col(rateuom)
      numeric_value: col(rate)
    filters:
      - drop_na(numeric_value)
