name: labevents
path: hosp/labevents.csv.gz
version: "3.1"
dataset: mimic-iv

columns:
  # subject_id and extentions
  - name: hadm_id
    type: int64
  - name: subject_id
    type: int64
  # db fields - times
  - name: charttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: comments
    type: string
  - name: flag
    type: string
  - name: itemid
    type: int64
  - name: labevent_id
    type: int64
  - name: order_provider_id
    type: string
  - name: priority
    type: string
  - name: ref_range_lower
    type: float32
  - name: ref_range_upper
    type: float32
  - name: specimen_id
    type: int64
  - name: value
    type: string
  - name: valuenum
    type: float32
  - name: valueuom
    type: string

join:
  - name: d_labitems
    path: hosp/d_labitems.csv.gz
    columns:
      # subject_id and extentions
      # db fields - times
      # db fields - values
      - name: category
        type: string
      - name: itemid
        type: int64
      - name: label
        type: string
      - name: fluid
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    stay_id: const("-1")

events:
  - name: labevent_id
    columns:
      time: col(charttime)
      code:
        - const("LABEVENT_ID")
      numeric_value: col(labevent_id)
  - name: specimen_id
    columns:
      time: col(charttime)
      code:
        - const("SPECIMEN_ID")
      numeric_value: col(specimen_id)
  - name: order_provider_id
    columns:
      time: col(charttime)
      code:
        - const("ORDER_PROVIDER_ID")
      text_value: col(order_provider_id)
    filters:
      - drop_na(text_value)
  - name: labevent
    columns:
      time: col(charttime)
      code:
        - const("LABEVENT")
        - col(label)
        - col(valueuom)
      numeric_value: col(valuenum)
      text_value: col(value)
    filters:
      - drop_na(text_value)
  - name: ref_range_lower
    columns:
      time: col(charttime)
      code:
        - const("REF_RANGE_LOWER")
      numeric_value: col(ref_range_lower)
    filters:
      - drop_na(numeric_value)
  - name: ref_range_upper
    columns:
      time: col(charttime)
      code:
        - const("REF_RANGE_UPPER")
      numeric_value: col(ref_range_upper)
    filters:
      - drop_na(numeric_value)
  - name: flag
    columns:
      time: col(charttime)
      code:
        - const("FLAG")
      text_value: col(flag)
    filters:
      - drop_na(text_value)
  - name: priority
    columns:
      time: col(charttime)
      code:
        - const("PRIORITY")
      text_value: col(priority)
    filters:
      - drop_na(text_value)
  - name: comments
    columns:
      time: col(charttime)
      code:
        - const("COMMENTS")
      text_value: col(comments)
    filters:
      - drop_na(text_value)
  - name: caregiver_store
    columns:
      time: col(storetime)
      code:
        - const("CG_ST")
    filters:
      - drop_na(time)
