name: labevents
path: hosp/labevents.csv.gz
version: "3.1"
dataset: mimic-iv

columns:
  # general codes
  - name: src_table_code
    type: string
    constant: hosp/labevents
  # codes
  - name: caregiver_store_code
    type: string
    constant: CG_ST # caregiver_storetime
  - name: comments_code
    type: string
    constant: COMMENTS
  - name: flag_code
    type: string
    constant: FLAG
  - name: labevent_code
    type: string
    constant: LABEVENT
  - name: labevent_id_code
    type: string
    constant: LABEVENT_ID
  - name: order_provider_id_code
    type: string
    constant: ORDER_PROVIDER_ID
  - name: priority_code
    type: string
    constant: PRIORITY
  - name: ref_range_lower_code
    type: string
    constant: REF_RANGE_LOWER
  - name: ref_range_upper_code
    type: string
    constant: REF_RANGE_UPPER
  - name: specimen_id_code
    type: string
    constant: SPECIMEN_ID
  # subject_id and extentions
  - name: hadm_id
    type: int64
  - name: stay_id
    type: int64
    constant: -1
  - name: src_db_id
    type: string
    constant: mimic
  - name: subject_id
    type: int64
  # db fields - times
  - name: charttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: comments
    type: string
  - name: flag
    type: string
  - name: itemid
    type: int64
  - name: labevent_id
    type: int64
  - name: order_provider_id
    type: string
  - name: priority
    type: string
  - name: ref_range_lower
    type: float32
  - name: ref_range_upper
    type: float32
  - name: specimen_id
    type: int64
  - name: value
    type: string
  - name: valuenum
    type: float32
  - name: valueuom
    type: string

join:
  - name: d_labitems
    path: hosp/d_labitems.csv.gz
    columns:
      # general codes
      # codes
      # subject_id and extentions
      # db fields - times
      # db fields - values
      - name: category
        type: string
      - name: itemid
        type: int64
      - name: label
        type: string
      - name: fluid
        type: string
    both_on:
      - itemid

event_defaults:
  subject_id: subject_id
  code_prefix:
    - src_table_code
  extension:
    hadm_id: hadm_id
    stay_id: stay_id
    src_db_id: src_db_id

events:
  - name: labevent_id
    columns:
      time: charttime
      code:
        - labevent_id_code
      numeric_value: labevent_id
  - name: specimen_id
    columns:
      time: charttime
      code:
        - specimen_id_code
      numeric_value: specimen_id
  - name: order_provider_id
    columns:
      time: charttime
      code:
        - order_provider_id_code
      text_value: order_provider_id
    filters:
      - drop_na(text_value)
  - name: labevent
    columns:
      time: charttime
      code:
        - labevent_code
        - label
        - valueuom
      numeric_value: valuenum
      text_value: value
    filters:
      - drop_na(text_value)
  - name: ref_range_lower
    columns:
      time: charttime
      code:
        - ref_range_lower_code
      numeric_value: ref_range_lower
    filters:
      - drop_na(numeric_value)
  - name: ref_range_upper
    columns:
      time: charttime
      code:
        - ref_range_upper_code
      numeric_value: ref_range_upper
    filters:
      - drop_na(numeric_value)
  - name: flag
    columns:
      time: charttime
      code:
        - flag_code
      text_value: flag
    filters:
      - drop_na(text_value)
  - name: priority
    columns:
      time: charttime
      code:
        - priority_code
      text_value: priority
    filters:
      - drop_na(text_value)
  - name: comments
    columns:
      time: charttime
      code:
        - comments_code
      text_value: comments
    filters:
      - drop_na(text_value)
  - name: caregiver_store
    columns:
      time: storetime
      code:
        - caregiver_store_code
    filters:
      - drop_na(time)
