name: microbiologyevents
path: hosp/microbiologyevents.csv.gz
version: "3.1"
dataset: mimic-iv

columns:
  # subject_id and extensions
  - name: hadm_id
    type: int64
  - name: subject_id
    type: int64
  # db fields - times
  - name: chartdate
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: charttime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storedate
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  - name: storetime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: ab_itemid
    type: int64
  - name: ab_name
    type: string
  - name: comments
    type: string
  - name: dilution_comparison
    type: string
  - name: dilution_text
    type: string
  - name: dilution_value
    type: float32
  - name: interpretation
    type: string
  - name: micro_specimen_id
    type: int64
  - name: microevent_id
    type: int64
  - name: order_provider_id
    type: string
  - name: order_provider_id
    type: string
  - name: org_itemid
    type: int64
  - name: org_name
    type: string
  - name: spec_itemid
    type: int64
  - name: spec_type_desc
    type: string
  - name: test_itemid
    type: int64
  - name: test_name
    type: string
  - name: test_seq
    type: int64
  - name: quantity
    type: string

event_defaults:
  subject_id: col(subject_id)
  extension:
    hadm_id: col(hadm_id)
    stay_id: const("-1")

events:
  - name: microevent_id
    columns:
      time: col(charttime)
      numeric_value: col(microevent_id)
  - name: specimen_id
    columns:
      time: col(charttime)
      numeric_value: col(micro_specimen_id)
  - name: order_provider_id
    columns:
      time: col(charttime)
      text_value: col(order_provider_id)
    callbacks:
      - drop_na(text_value)
  - name: spec
    columns:
      time: col(charttime)
      code:
        - col(spec_type_desc)
      numeric_value: col(spec_itemid)
  - name: test_item
    columns:
      time: col(charttime)
      code:
        - col(test_name)
      numeric_value: col(test_itemid)
  - name: organism
    columns:
      time: col(charttime)
      code:
        - col(org_name)
      numeric_value: col(org_itemid)
  - name: antibiotic
    columns:
      time: col(charttime)
      code:
        - col(ab_name)
      numeric_value: col(ab_itemid)
  - name: dilution
    columns:
      time: col(charttime)
      text_value: col(dilution_text)
      numeric_value: col(dilution_value)
      # dilution_comparison
    filters:
      - drop_na(numeric_value)
      - drop_na(text_value)
  - name: interpretation
    columns:
      time: col(charttime)
      text_value: col(interpretation)
    filters:
      - drop_na(text_value)
  - name: comments
    columns:
      time: col(charttime)
      text_value: col(comments)
    filters:
      - drop_na(text_value)
  - name: comments
    columns:
      time: col(charttime)
      text_value: col(comments)
    filters:
      - drop_na(text_value)
  - name: caregiver_store
    columns:
      time: col(storetime)
    filters:
      - drop_na(time)
