name: omr # online medical record
path: hosp/omr.csv

fields:
  # general codes
  - name: src_table_code
    type: string
    constant: hosp/omr
  # codes
  - name: omr_code
    type: string
    constant: OMR
  # subject_id and extentions
  - name: hadm_id
    type: int64
    constant: -1
  - name: stay_id
    type: int64
    constant: -1
  - name: src_db_id
    type: string
    constant: mimic 
  - name: subject_id
    type: int64
  # db fields - times
  - name: chartdate
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: result_name
    type: string
  - name: result_value
    type: string
  - name: seq_num
    type: int64

events:
  - name: value
    fields:
      subject_id: subject_id
      time: chartdate
      code: 
        - src_table_code
        - omr_code
        - result_name
      text_value: result_value
      numeric_value: seq_num
      extension:
        hadm_id: hadm_id
        stay_id: stay_id
        src_db_id: src_db_id