name: services
path: hosp/services.csv.gz
version: "3.1"
dataset: mimic-iv

columns:
  # subject_id and extentions
  - name: hadm_id
    type: int64
  - name: subject_id
    type: int64
  # db fields - times
  - name: transfertime
    type: datetime
    params:
      format: "%Y-%m-%d %H:%M:%S"
  # db fields - values
  - name: curr_service
    type: string
  - name: prev_service
    type: string

event_defaults:
  subject_id: col(subject_id)
  time: col(transfertime)
  code_prefix:
    - const("hosp/services")
  extension:
    hadm_id: col(hadm_id)
    stay_id: const("-1")
    src_db_id: const("mimic")

events:
  - name: prev_service
    columns:
      code:
        - const("PREV_SERVICE")
        - col(prev_service)
  - name: curr_service
    columns:
      code:
        - const("PREV_SERVICE")
        - col(curr_service)
