name: Extraction
version: 1.0.0

config_files:
  - path: /workspaces/config/dataset/mimic-iv/3.1/
  - path: /workspaces/config/dataset/eicu/2.0/

config:
  data:
    - name: mimic-iv
      path: /workspaces/example/data/mimic-iv/
    - name: eicu
      path: /workspaces/example/data/eicu/
