name: test_pipeline
version: 1.0.0

project:
  path: /workspaces/example/output/project
  overwrite: true

steps:
  - name: ExtractionStep
    config:
      workspace:
        name: extraction
      files:
        - name: mimic-iv
          path: /workspaces/config/dataset/mimic-iv/3.1/
          dataset_path: /workspaces/example/data/mimic-iv/3.1/
        - name: eicu
          path: /workspaces/config/dataset/eicu/2.0/
          dataset_path: /workspaces/example/data/eicu/2.0/

  - name: CollectionStep
    config:
      dataset:
        name: raw
      collecting:
        - name: extraction
