version: '3.8'

services:
  openicu:
    container_name: openicu
    extra_hosts:
      - host.docker.internal:host-gateway
    init: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - "8787:8787"
    environment:
      - no_proxy="127.0.0.1,localhost"
      - NO_PROXY="127.0.0.1,localhost"
    env_file:
      - dev.env
      - path: env
        required: false
    volumes:
      - ..:/workspaces:cached
      - ${DATA_FOLDER:-/home/$USER/}:/workspaces/example/data
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
