name: alkaline_phosphatase
version: 1.0.0
unit: IU/L

extension_columns:
  dataset: col("dataset")
  table: col("table")

mappings:
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: labevents
      event: result
      code: (50863//Alkaline Phosphatase)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
