name: potassium
version: 1.0.0
unit: mE1/L

extension_columns:
  dataset: col("dataset")
  table: col("table")

mappings:
  - pattern:
      dataset: mimic-iv
      version: "3.1"
      table: labevents
      event: labevent
      code: .*?(Potassium)
    columns:
      numeric_value: col(numeric_value)
      text_value: col(text_value)
